### ISSUE TITLE
string.h No such file or directory

### ISSUE THREAD

**Issue by mrhappy200** [Frederic98/SteamDeckGadget#1]
Hello, this is not working very well for me, when I run `make` I get this error 

> g++ -std=c++11 -o SteamworksPy.so -shared -fPIC SteamworksPy.cpp -l steam_api -L.
> 
> In file included from sdk/steam/steam_api_common.h:233,
>                  from sdk/steam/steam_api.h:21,
>                  from SteamworksPy.cpp:16:
> sdk/steam/steam_api_internal.h:14:10: fatal error: string.h: No such file or directory
>    14 | #include <string.h>
>       |          ^~~~~~~~~~
> compilation terminated.
> make: *** [Makefile:2: makeall] Error 1

**Comment by Frederic98** [comment]
Yeah, i haven't had much luck either with Arch. I compiled on an Ubuntu machine and just copied the .so to the deck, since it's just the same architecture.
I'll see if I can upload a release to GitHub with precompiled binaries.

**Comment by mrhappy200** [comment]
That would be great, thanks for the fast response. I will try to spin up an Ubuntu vm to build this.

**Comment by mrhappy200** [comment]
I will leave the issue open though since it is not intended, is that okay with you?

**Comment by parkerlreed** [comment]
Steam deck doesn't ship headers so you have to reinstall some of the base packages if you want to compile on the deck itself (or use distrobox)

string.h is part of man-pages

**Comment by Frederic98** [comment]
I've made a release for (my fork of) SteamworksPy, and added a script that sets up the whole project on the deck.  
You should now be able to just clone this repo and run ./setup to have all the dependencies sorted out.
